### ISSUE TITLE
Bugsnag is flagged as non-certified ad SDK

### ISSUE THREAD

**Issue by Mohamed-Abbas** [bugsnag/bugsnag-android#1199]
### Describe the bug
We've recently submitted our Android app to the Google Play Store and have been flagged due to Google thinking Bugsnag SDK is an Ad SDK. Our app is specifically directed for children, and we are aware of not using non-certified ad SDKs.

### Steps to reproduce
1. Create an APP.
2. Add Bugsnag SDK
2. Register the APP on the Google play families program
3. Submit the App for review to Google Play Store

### Environment
* Bugsnag version: com.bugsnag:bugsnag-android:4.22.3

### Context
Google Play Support
<img width="1412" alt="Screen Shot 2021-03-18 at 2 16 14 PM" src="https://user-images.githubusercontent.com/26598024/111624637-9c5c5980-87f4-11eb-8e33-62853d43443c.png">

**Comment by yousif-bugsnag** [comment]
Hi @Mohamed-Abbas,

We would recommend appealing this decision with Google, since Bugsnag is not an Ad SDK. Its sole purpose is to report data on application errors and crashes to app developers. It does not serve ads under any circumstances, nor does it expose any data to any other party besides the app developer.

We're aware of a very small number of other customers who have run into the same issue, and we're looking into ways that we can influence Google's policy on this, but until then it's worth appealing their decision as we believe it's incorrect.

**Comment by mattdyoung** [comment]
@Mohamed-Abbas 
We have now discussed this with Google Play who have agreed to allow use of the Bugsnag SDK for apps in their Families program. We'd recommend publishing a new version of your app including Bugsnag and please do let us know if you encounter any further issues.
