### ISSUE TITLE
crash is not showing on dashboard on development phase. Only bugsnag.notify() is getting captured in dashboard.

### ISSUE THREAD

**Issue by shiwanjalyFareye** [bugsnag/bugsnag-android#1216]
crash is not showing on dashboard on development phase. Only bugsnag.notify() is getting captured in dashboard.
bugsnag : 7.3.3
react-native : 0.63.4

**Comment by mattdyoung** [comment]
This is likely due to React Native's [In-app Error screen](https://facebook.github.io/react-native/docs/debugging.html#in-app-errors-and-warnings) interfering with the automatic capture of unhandled native crashes.

If you want to send these unhandled errors to Bugsnag in the course of development, we recommend running your app in [release mode](https://facebook.github.io/react-native/docs/running-on-device.html):
https://docs.bugsnag.com/platforms/react-native/react-native/#reporting-unhandled-errors

I'd recommend trying running the app in release mode. If you still see issues with capture of unhandled crashes when running in release mode can you write in to support@bugsnag.com with full details of how you're configuring Bugsnag and testing this so we can investigate further?
