### ISSUE TITLE
Configurable max breadcrumb count for NDK events

### ISSUE THREAD

**Issue by scrossuk** [bugsnag/bugsnag-android#1219]
### Description

Number of breadcrumbs is always limited to 25 for NDK events (due to hardcoded constant), whereas Kotlin errors can set up to 100 breadcrumbs. [The docs](https://docs.bugsnag.com/platforms/android/configuration-options/#maxbreadcrumbs) say:

> For NDK events the maximum number of breadcrumbs is fixed at the default of 25 and cannot be amended.

**Describe the solution you'd like**

Ideally the NDK plugin would use the same value as set by Kotlin. An alternative would be to have a separate configurable limit (e.g. `bugsnag_set_max_breadcrumbs` function).

**Describe alternatives you've considered**

Custom build of NDK plugin, but it's a little awkward for just this issue.

**Comment by xander-jones** [comment]
Hi @scrossuk 👋. We plan to review NDK breadcrumb limits in due course, including the size of data within the breadcrumb itself. We don't have a firm ETA for when this is going to happen, but it's on our radar 😊

**Comment by hannah-smartbear** [comment]
Hi @scrossuk, 

We just wanted to let you know that since [v6.5.0](https://github.com/bugsnag/bugsnag-android/releases/tag/v6.5.0) of `bugsnag-android`, the number of breadcrumbs for NDK events can be configured by the [maxBreadcrumbs config option](https://docs.bugsnag.com/platforms/android/configuration-options/#maxbreadcrumbs). 

Please let us know if you have any questions about this.
