### ISSUE TITLE
Gradle sync issues on applying com.bugsnag.android.gradle plugin

### ISSUE THREAD

**Issue by hzaun** [bugsnag/bugsnag-android#1767]
Please checkout our [documentation](https://docs.bugsnag.com/platforms/android/) for guides, references and tutorials.

If you have questions about your integration please contact us at [support@bugsnag.com](mailto:support@bugsnag.com).

Alternatively, view additional options at [support.md](../SUPPORT.md).

---
project/ build.gradle:

`buildscript {
    dependencies {
        ...
        classpath "com.bugsnag:bugsnag-android-gradle-plugin:5.0.1"
    }
}`

app/ build.gradle:
`apply plugin: "com.bugsnag.android.gradle"` -> Error caused by this line.

`dependencies {
    debugImplementation "com.bugsnag:bugsnag-android:5.27.0"
}`

ANDROID_GRADLE_PLUGIN_VERSION=4.2.0

---

>Unable to find method ''void com.android.build.api.dsl.CommonExtension.onVariants(kotlin.jvm.functions.Function1)''
'void com.android.build.api.dsl.CommonExtension.onVariants(kotlin.jvm.functions.Function1)'
>
>Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
>
>Re-download dependencies and sync project (requires network)
>The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
>
>Stop Gradle build processes (requires restart)
>Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.
>
>In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.
---

From what I can see, the error is due to incompatibility between the gradle plugin and the bugsnag version.
Can you tell me which version I can use to make use of the plugin?

**Comment by luke-belton** [comment]
Hi @hzaun - were you building a debug variant when you saw this error? You have `debugImplementation "com.bugsnag:bugsnag-android:5.27.0"` in your apps `build.gradle` file, but you'll likely want to use `implementation "com.bugsnag:bugsnag-android:5.27.0"` here instead.

Otherwise this doesn't necessarily look like a Bugsnag issue as such - have you followed the steps suggested by the Gradle output to resolve this? Could you write into support@bugsnag.com, sharing the full contents of your `build.gradle` files if possible please?

**Comment by johnkiely1** [comment]
Hi @hzaun, I'm going to assume Luke's suggestion resolves your issue and close this out. But do let us know if that is not the case and we can reopen.
