### ISSUE TITLE
Determining the full Source File Path for a Crash Report

### ISSUE THREAD

**Issue by handstandsam** [bugsnag/bugsnag-android#1922]
## Background
Bugsnag provides a stacktrace with fully qualified method/class names, as well as the filename (i.e. `Utilities.kt`) in a crash report.

## Problem
I am looking to assign bugs automatically to an owner.  Ownership is tied to files in this project.  It can be challenging to disambiguate which `Utilities.kt` file this is, if the are multiple across a large repository.

## Question
How can we determine the originating full source path via a crash report?  I am aware of the fully qualified method/class name in the stack trace, but am unaware of how to determine what file that is in.

Thanks!

**Comment by clr182** [comment]
Hi @handstandsam 

I can see you've opened another ticket with us discussing this in more depth. 
As discussed, because proguard fields do not contain the full file paths for mappings, we are unable to make that information available on mapped events in BugSnag.

If you are able to approximate the full path of your Android errors, you can potentially add this [as custom metadata](https://docs.bugsnag.com/platforms/android/customizing-error-reports/#addmetadata) and then [automatically assign errors based on custom metadata](https://docs.bugsnag.com/product/automatic-error-assignment/#custom-metadata). Additionally, if you were not aware of it already, you may be interested to know about a new feature in automatic error assignment, where you can now assign errors based on the [fully-qualified method name](https://docs.bugsnag.com/product/automatic-error-assignment/#code:~:text=Code%20matches%20using%20method) (including the class and package).

I should note that we have an [update an error endpoint](https://bugsnagapiv2.docs.apiary.io/#reference/errors/errors/update-an-error) that you can use to assign errors programmatically.

**Comment by mclack** [comment]
Hi @handstandsam 

As there hasn't been any activity here for a while, we are now closing this issue.

If you continue to experience any problems, please feel free to reopen this issue along with any additional relevant information, or open a ticket with us directly by contacting [support@bugsnag.com](mailto:support@bugsnag.com).
