### ISSUE TITLE
Init Bugsnag in a non-Application context?

### ISSUE THREAD

**Issue by mrfaa** [bugsnag/bugsnag-android#353]
Is it absolutely necessary to init bugsnag in an application class (e.g. "public class MyApp extends Application")?

What may be consequences if initializing it not in an application class?

Thanks in advance for an answer!

**Comment by fractalwrench** [comment]
We would strongly recommend initialising in a custom `Application` class rather than your launch `Activity`. There are a couple of reasons for this, which I'll list here:

- Any exceptions which are thrown between `Application#onCreate` and `Activity#onCreate` would not be captured.
- [Automatic Breadcrumbs](https://docs.bugsnag.com/platforms/android/sdk/#logging-breadcrumbs) cannot be captured for activity lifecycle events and broadcasts until the SDK has been initialised, meaning there would be less useful metadata attached to errors which occur early in an app's session.
- `Bugsnag.init(this)` should only really be called once, which is not guaranteed in an activity.
- If an app is launched via a different entrypoint, such as a Notification launching a different Activity, it's possible that Bugsnag might never be initialised if a developer assumed that `MainActivity` would always be launched first.

If you had any specific concerns about initialising in an `Application` subclass, please let us know and we'll do our best to answer.

**Comment by mrfaa** [comment]
@fractalwrench great answer! thank you very much!
