### ISSUE TITLE
java.lang.ArrayStoreException

### ISSUE THREAD

**Issue by YangKunCheng** [bugsnag/bugsnag-android#558]
java.lang.ArrayStoreException · source[9] of type java.lang.String cannot be stored in destination array of type java.lang.Thread[]

ThreadState.java

**Comment by mattdyoung** [comment]
Hi @YangKunCheng 

It's not clear to us under what circumstances you're seeing that error.

Can you share a code example with us of how to reproduce?

Thanks!

**Comment by YangKunCheng** [comment]
We are not clear the crash scenes too.

there is one of the crash stack below.

System.java:-2java.lang.System.arraycopy	
ArrayList.java:523java.util.ArrayList.toArray	
AbstractCollection.java:343java.util.AbstractCollection.toArray	
360Security:-1com.bugsnag.ThreadState.sortThreadsById	
360Security:-1com.bugsnag.ThreadState.<init>	
360Security:-1com.bugsnag.SessionStore$a.<init>
360Security:-1com.bugsnag.JsonWriter.write	
360Security:-1com.bugsnag.ExceptionHandler.uncaughtException
360Security:51com.crashlytics.android.core.r.uncaughtException	
360Security:76com.aiming.mdt.sdk.util.CrashHandler$1.run	
Thread.java:818java.lang.Thread.run

OS VERSIONS:6.0.1
Manufacturers: FUJITSU

**Comment by mattdyoung** [comment]
@YangKunCheng 
OK - thanks for the report. We're going to try and reproduce the issue and will let you know the outcome.

**Comment by abigail-bugsnag** [comment]
Hi @YangKunCheng - We don't quite understand the circumstances in which this can happen. This error occurs when attempting to put a String into a Thread[] variable, but this does not seem to occur anywhere in ThreadState.java.

Can you provide us some additional information including: 
- device manufacturer
- % of crashes vs users
- which version of bugsnag-android you are using
- what the name is of your Bugsnag organisation account

Feel free to write into support@bugsnag.com with this information instead of providing it here.

**Comment by YangKunCheng** [comment]
device manufacturer：FUJITSU
OS VERSIONS:6.0.1
Rate：We only met this bug once.
Account：lucas.cheung@mobisummer.com

**Comment by abigail-bugsnag** [comment]
Thank you for the additional information @YangKunCheng. We have been continuing to look into this. This looks to be a specific issue which is only affecting certain devices.
We are still trying to create a suitable reproduction case. If you have a reproduction example then please let us know :)

**Comment by johnkiely1** [comment]
This has been fixed in [V5.0.0](https://github.com/bugsnag/bugsnag-android/releases/tag/v5.0.0)
