### ISSUE TITLE
Increase max breadcrumbs

### ISSUE THREAD

**Issue by pyricau** [bugsnag/bugsnag-android#891]
At Square we currently use a custom tab to log our own breadcrumbs. I was looking at migrating us to using Bugsnag breadcrumbs. In Bugsnag 4.x there was no max breadcrumb, while in 5.0 the max is 100. We currently have a max of 400.

I can't use the 4.x breadcrumbs, the implementation is clearly broken: it serializes the entire stream of breadcrumbs on every add() just to check the json isn't greater than 4Kb (I'm glad to see this was removed in 5.x).

**Comment by pyricau** [comment]
Actually, I did find a workaround until this is fixed, by creating a package spy that overrides the range check:

```
    Configuration configuration = new Configuration(apiKey) {
      @Override public void setMaxBreadcrumbs(int maxBreadcrumbs) {
        impl.setMaxBreadcrumbs(maxBreadcrumbs);
      }
    };
```

**Comment by xander-jones** [comment]
Hey @pyricau, we have a maximum number of breadcrumbs due to the notification endpoint having a maximum allowance for a payload of 1MB. This helps ensure that the maximum size is not exceeded, and so that Bugsnag can remain a lightweight footprint on an app. We're unlikely to increase this maximum value across the board as it could lead to issues for other users. Thanks for letting us know about the override workaround above.

Previously, the 4KB limit on individual breadcrumbs was intended to keep this payload down, but this concept has been scrapped from our notifier specification, and will eventually be removed from all notifiers if it exists. (It's gone from Cocoa, Javascript, and Android specifically so far)

**Comment by pyricau** [comment]
@xander-jones thanks for your response. So it looks like the max size for breadcrumbs is 2 bytes per char * 140 chars per breadcrumb * 100 breadcrumbs = 28Kb. We really only need 4 times that, ie 122Kb. I understand trying to keep this under control, so we'll have to resort to reflection or forking to stick to our 400K.

On a related note, what happens when we go over the 1MB limit / is there any way for us to know when that happens / what our average payload looks like? Either client side or on the dashboard?

**Comment by phillipsam** [comment]
Hi @pyricau if the payload limit is exceeded, the payloads will be dropped. If you would like to get in touch at support@bugsnag.com, we can discuss this further.
