### ISSUE TITLE
Unsatisfielinkerror triggered by bugsnag

### ISSUE THREAD

**Issue by stoyicker** [bugsnag/bugsnag-android#899]
### Expected behavior
Bugsnag not causing a crash because of (I assume) an architecture it doesn't support

### Observed behavior
Bugsnag fails to load the so file by throwing an unchecked exception. If there's an architecture that is not supported I'd like to be forced to handle the case where loading fails, or at least, have it fail silently instead of crashing ny app on a user device

### Steps to reproduce
Not sure, but I'd say just init bugsnag.

### Version
4.22.3

### Additional information
Only got reports on this on a device called vivo x9.

[bugsnag_error_stacktrace_java.lang.UnsatisfiedLinkError_event_5f0677b8005b80bdc7070000.txt](https://github.com/bugsnag/bugsnag-android/files/4899259/bugsnag_error_stacktrace_java.lang.UnsatisfiedLinkError_event_5f0677b8005b80bdc7070000.txt)

**Comment by xander-jones** [comment]
Hey @stoyicker, this has been fixed in [v5.0.0](https://github.com/bugsnag/bugsnag-android/releases/tag/v5.0.0) (through PR https://github.com/bugsnag/bugsnag-android/pull/861) :tada:

Please note that v5.0.0 has some breaking changes, so you'll want to check out [UPGRADING.md here](https://github.com/bugsnag/bugsnag-android/blob/v5.0.0/UPGRADING.md) if you do upgrade.
