### ISSUE TITLE
OnErrorCallback not invoked during NDK crashes

### ISSUE THREAD

**Issue by baolongnt** [bugsnag/bugsnag-android#951]
### Describe the bug
The callback set in the Configuration object is not being invoked when an NDK crash occurs

### Steps to reproduce
1. Start BugSnag using the following config
```java
configuration.addOnError(event -> {
    Log.d(TAG, "onError: " + event);
    event.addMetadata("section", "name", "value);
    return true;
});
```
2. Generate an NDK crash
3. Callback is not invoked and data does not show on the web UI

### Environment
* Android version: 10
* Bugsnag version: 5.2.0
* Emulator or physical device: emulator

**Comment by mattdyoung** [comment]
Hi @baolongnt 

This behavior is by design - OnErrorCallbacks set in Java/Kotlin are executed for handled errors sent from native C/C++ code, but they will not be triggered for native crashes as the system terminates immediately.

Please see our documentation for a full explanation and details of how to add callbacks for native crashes in C/C++:
https://docs.bugsnag.com/platforms/android/customizing-error-reports/#updating-events-using-callbacks
